module.exports = {
  obj: {
    landing: {
      id: "landing",
      hex: "#ffe500",
      logo_url: "img/logo/logo_icon_black.jpg",
      title: "Evènements d'entreprise",
      //navie_opts: "revealed",
      navie_active: "landing",
      page_url: "/index.html",
      page_title: "Instant-B | Animations entreprise, soirées, bars à thème et évènement",
      page_description: "Découvrez nos animations pour vos évènements d'entreprise : bar à smoothies, fontaine de chocolat, animation crêpes, bar à cocktails, food truck, buffets traiteurs, animations glaces… Votre évènement entreprise sur mesure : soirées, stands, séminaires, avec Instant-B."
    },
    vita: {
      id: "vita",
      index: 1,
      slider_start: true,
      hex: "#6cad2e",
      title: "Instants vitaminés",
      desc: "De savoureux fruits et légumes frais transformés à la demande en smoothie, salade ou soupe sur votre événement !",
      hashtags: ["hash 1", "hash 2", "hash 3"],
      logo_url: "img/logo/logo_text_green_mk.png",
      main_url: "img/vita_main.jpg",
      navie_active: "services",
      page_url: "/instants-vitamines.html",
      page_title: "Instant vitaminé | Animation smoothies, bar à salades, bar à soupes",
      page_description: "Des fruits et légumes frais mixés et préparés devant vos convives, nos animations smoothies, salades et soupes sauront séduire vos invités !"
    },
    yummy: {
      id: "yummy",
      index: 2,
      hex: "#f7b55c",
      title: "Instants gourmands",
      desc: "Notre fontaine de chocolat et nos animations crêpes, gaufres et café gourmands vous feront oublier que la gourmandise est un vilain défaut !",
      hashtags: ["hash 1", "hash 2", "hash 3"],
      logo_url: "img/logo/logo_text_orange_mk.png",
      main_url: "img/gourmand_main.jpg",
      navie_active: "services",
      page_url: "/instants-gourmands.html",
      page_title: "Instant gourmand | Fontaîne de chocolat, animations crèpes, gaufres, cafés et thés gourmands",
      page_description: "Notre fontaine de chocolat, nos animations crêpes ou gaufres ainsi que notre bar à cafés, thés et chocolats gourmands émerveilleront les papilles de vos invités."
    },
    child: {
      id: "child",
      index: 3,
      hex: "#ed57a1",
      title: "Instants souvenirs d'enfance",
      desc: "Des animations originales qui transporteront vos convives en enfance le temps de votre événement !",
      hashtags: ["hash 1", "hash 2", "hash 3"],
      logo_url: "img/logo/logo_text_pink_mk.png",
      main_url: "img/enfance_main.jpg",
      navie_active: "services",
      page_url: "/instants-souvenirs.html",
      page_title: "Instant souvenir d'enfance | Animation barbe à papa, pop-corn, candy bar",
      page_description: "Nos animations barbe à papa, pop-corn ou notre candy bar renverront vos invités quelques années en arrière."
    },
    apero: {
      id: "apero",
      index: 4,
      hex: "#eb6d5b",
      title: "Instants apéritifs",
      desc: "Nos bar à cocktails, vins, champagnes et bières rendront vos réceptions festives et inoubliables !",
      hashtags: ["hash 1", "hash 2", "hash 3"],
      logo_url: "img/logo/logo_text_red_mk.png",
      main_url: "img/apero_main.jpg",
      navie_active: "services",
      page_url: "/instants-aperitifs.html",
      page_title: "Instant apéritif | Bar à cocktails, champagne, vin, bière",
      page_description: "Notre bar à cocktail, notre bar à vins et notre bar à bière sont idéals pour tous se retrouver lors d’un moment convivial. Nos barmen sauront surprendre vos invités avec leurs différentes recettes et mise en scène (flair) !"
    },
    snack: {
      id: "snack",
      index: 5,
      hex: "#c68d4e",
      title: "Instants snacking",
      desc: "Découvrez tous nos concepts de Food Truck en entreprise à consommer à chaque instant : Bagels, Hot-Dogs, Burgers, Panini, Pizzas…",
      hashtags: ["hash 1", "hash 2", "hash 3"],
      logo_url: "img/logo/logo_text_brown_mk.png",
      main_url: "img/snacking_main.jpg",
      navie_active: "services",
      page_url: "/instants-snacking.html",
      page_title: "Instant snacking | bagels, hot-dogs, burgers, paninis, pizzas, croques monsieur…",
      page_description: "Découvrez tous nos concepts Snacking de Food truck en entreprise à consommer à chaque instant : bagels, hot-dogs, burgers, paninis, pizzas, croques monsieur… Tous nos produits sont réalisés sur place à la demande de vos invités !"
    },
    fresh: {
      id: "fresh",
      index: 6,
      hex: "#5FC5F0",
      title: "Instants fraîcheur",
      desc: "De délicieuses animations qui rafraichirons vos invités !",
      hashtags: ["hash 1", "hash 2", "hash 3"],
      logo_url: "img/logo/logo_text_blue.png",
      main_url: "img/fraicheur_main.jpg",
      navie_active: "services",
      page_url: "/instants-fraicheur.html",
      page_title: "Instant fraîcheur | Animation frozen yogurt, glace, sorbet moléculaire",
      page_description: "L’instant fraicheur c’est une multitude d’animations pour rafraichir vos convives : glaces à l’italienne, frozen yogurt, granités, sorbets moléculaires."
    },
    cater: {
      id: "cater",
      index: 7,
      hex: "#ec594f",
      title: "Instants traiteur",
      desc: "Hello world",
      hashtags: ["hash 1", "hash 2", "hash 3"],
      logo_url: "img/logo/logo_text_red_mk.png",
      main_url: "img/traiteur_main.jpg",
      navie_active: "services",
      page_url: "/traiteur.html",
      page_title: "Instant traiteur | Buffet terroir, pièce cocktail, petit-four, ",
      page_description: "Régalez vos convives avec nos différents buffets traiteurs déclinables sous de nombreuses thématiques : pièces cocktails, pièces japonaises, pièces orientales, buffet terroir, plateaux de fromages…"
    },
    events: {
      id: "events",
      hex: "#ffe500",
      title: "Votre évènement clé en main",
      desc: "Régalez vos convives avec nos différents buffets traiteurs déclinables sous de nombreuses thématiques : pièces cocktails, pièces japonaises, pièces orientales, buffet terroir, plateaux de fromages…",
      types: [
        {name: "Lieux", icon_url: "img/icons/houses.svg"},
        {name: "Food", icon_url: "img/icons/cutlery.svg"},
        {name: "Musique", icon_url: "img/icons/headphones.svg"},
        {name: "Photos", icon_url: "img/icons/photo-camera.svg"},
        {name: "Transport", icon_url: "img/icons/van.svg"},
        {name: "Divertissements", icon_url: "img/icons/headphones.svg"}
      ],
      logo_url: "img/logo/logo_text_yellow_mk.png",
      main_url: "img/events.jpg",
      navie_active: "events",
      page_url: "/evenements.html",
      page_title: "Votre évènement clé en main | Salle, lieu, matériel, DJ, photographe, magicien…",
      page_description: "Instant-B vous accompagne sur la gestion clé en main de vos événements : lieux, restauration, performers, matériels"
    },
    quote: {
      id: "quote",
      hex: "#ffe500",
      logo_url: "img/logo/logo_text_yellow_mk.png",
      // main_url: "img/vita_main.jpg",
      navie_active: "quote",
      page_url: "/devis.html",
      page_title: "Instant-B | Devis",
      page_description: "Votre devis pour tout le catalogue de nos prestations en moins de 48 heures !"
    },
    photos: {
      id: "photos",
      hex: "#ffe500",
      navie_active: "photos",
      logo_url: "img/logo/logo_text_yellow_mk.png",
      page_url: "/photos.html",
      page_title: "Instant-B | Photos",
      page_description: "Découvrez notre gallerie de photos prises lors de nos évènements."
    }
  }
};
